### PR TITLE
JSON Schema for vega2

### PR DESCRIPTION
**Pull request by marcprux**
A JSON Schema (draft 4) for a vega2 spec, as requested in https://github.com/trifacta/vega/issues/136. It is mostly complete, but the signals and interactors parts need further specification and documentation. The schemas currently validate against all the example specs, and a test case is included to ensure that they continue to validate (using the "z-schema" JSON Schema validator).

The schema is currently fairly open-ended (e.g., we don't force transforms to conform to a specific enumeration nor do we try to validate transform properties) in order the preserve extensibility.

Areas that still need to be fleshed out are undocumented properties (marked with "Documentation forthcoming"), and further enumeration of valid properties (which are usually marked with additionalProperties: true).

### CODE REVIEW

**Comment by marcprux** [comment]
The JSON schema got broken by the changes in https://github.com/uwdata/vega/pull/46. Is there any interest in this contribution? If so, I'll update it. If not, please just close it.

**Comment by arvind** [comment]
Hi Marc, apologies for the slow response to this. I appreciate the PR because it's forced me to think more about how to support JSON schema as part of Vega. My biggest concern, and this is highlighted by #46, is that a separate JSON schema has the potential of falling out-of-date with changes made to other parts of the code base (i.e., developers would need to remember to make a change in two places, and we would have to check for this during PR merges). 

One idea I've been playing around with in my head is we create a `Parser` class with a `_schema` member variable and a `parse` method. Each part of the parser (i.e., each file under the `parse/`directory) would subclass this file and define the schema it is associated with. The `parse` method would then test input specs against the schema, and only valid property definitions would pass through. This prevents a parser from implementing any functionality that isn't documented within the schema (i.e., a **"self-documenting" parser**).

There are a couple of issues I haven't yet worked through though:
1. `enter`, `update`, and `exit` can contain any properties, if Vega doesn't recognize them, it just passes them through to the generated scene graph items. I don't know enough about JSON schema yet to know whether we can document only part of the valid properties, and then leave a wild card in there?
2. What is the performance impact of run-time validation of schemas? Perhaps it should be behind a flag?

What are your thoughts on this? I had been meaning to post this to the google group to solicit ideas, but have still been catching up on things after a vacation. Perhaps you'd like to kick it off? :)

**Comment by marcprux** [comment]
Arvind-

The self-documenting parser idea sounds attractive, but it seems like a major undertaking given the current ad-hoc "parsing" that is happening. You are correct that adding a separate JSON schema does introduce the potential for the schema to drift out of sync with the actual parsing process, and so threatens to violate DRY principles. However, given that this PR comes with a test suite that validate all of the examples against the schema, any changes to an example spec that wind up failing the schema validation tests would act as a warning that the person who made the parser change might also need to update the schema. And one could argue that anything the vega spec can express aught to be exercised by at lease one example spec, especially now that all the example specs' rendered output is being validated by my tests cases in https://github.com/uwdata/vega/pull/44 https://github.com/uwdata/vega/pull/44. So I do think there will be some natural pressure to keep the JSON schema in sync with the actual behavior.

All that being said, my motivation for committing the schema is both orthogonal and more modest than proposing a change to how parsing is done. I view it as important for two reasons:

A. Documentation: vega2 will eventually need to be documented, and the descriptions for the various schema elements could be used as the source for automating that documentation generation. I'm sure someone somewhere has an awesome JSON-Schema-to-Markdown tool that can be automatically run to generate stuff for the project's wiki, but if not, I'll build one.

B. Interoperability: I needed this JSON schema because I need to generate valid vega specs from other languages; it is much easier to generate the various model types from some well-formed schema than it is to write it all by hand in 3 different languages. Regardless of whether this PR is accepted, I'll be maintaining my own version of the JSON Schema for this reason alone, so I figured the rest of the world aught to benefit from it as well (especially projects like vegalite).

In response to your two specific issues:
1. I'm not in love with this new ability for enter, update, and exit to contain _any_ properties, but I wasn't privy to the design considerations that went into that. The way I handle this fact that the properties set "additionalProperties" for "mark-prop" to say that type="object"; that means that it can contain any unenumerated properties, as long as they are object types (and not, say, a number). It's a very loose constraint, but it seemed to be the best assertion I could make.
2. My PR doesn't do any runtime validation of the schema at all, so there in no runtime impact right now; I though putting in runtime support would be presumptuous without any initial discussion. It is purely there for test-case example spec validation, third-party language support, and perhaps eventual documentation generation. That being said, it might be nice to eventually include the schema in vega and do some runtime validation in order to help people identify syntax errors that their spec (the current lack of which contributes to vega's steep learning curve). But I haven't touched the runtime at all in this PR.

Anyway, I hope this gets accepted, but even if it doesn't, I'll be maintaining it on my own. Let me know if I should update the PR so it passes the tests with the most recent commits.

```
-Marc
```

**Comment by marcprux** [comment]
I forgot to mention one more reason why I implemented the schema: we could use a framework like http://jeremydorn.com/json-editor/ to create a richer demo editor for vega than the current free-form manual JSON editor.html. The schema works somewhat out of the box right now if you paste the schema text into the bottom of that page.

**Comment by arvind** [comment]
Hi Marc, I'm closing this PR in favour of #62 where I'm trying to achieve a compromise among the issues I discussed above. In particular, I'm breaking up the schema into more manageable pieces, and defining them within the corresponding parser files. The hope is that this makes it easier to keep the schema up-to-date. And, as you said, new test cases can increase our confidence in the schema. #62 is still a work-in-progress, but feel free to leave my suggestions/advice, or contribute there.

**Pull request closed without merging**
