### PR TITLE
Multi group by

### PR DESCRIPTION
**Pull request by domoritz**
- [x] make aggregate tests pass
- [x] fix scale
- [ ] ~~clean up aggregates on reset~~
- [x] fix examples

### CODE REVIEW

**Comment by arvind** [comment]
Sorry, so why is this marked WIP? What isn't complete? I'm a little wary of merging incomplete changes into the main v2 branch...

**Comment by domoritz** [comment]
I need to clean up a bunch of stuff, which I'll do tomorrow. I just wanted to see the summary of the changes. The way I use WIP means that you don't need to bother about reviewing anything yet; or even look at it.

**Comment by domoritz** [comment]
@arvind This is ready for review.

**Comment by arvind** [comment]
Ok, sounds good!

**Comment by arvind** [comment]
Thanks for the PR @domoritz. It looked good for the most part; my commit messages summarize the changes I made. Let me know if you have any questions :)

**Comment by domoritz** [comment]
The changes make sense to me. I'm still a bit shaky on the distinction between cell and tuple, though.

**Comment by arvind** [comment]
The distinction is basically what is internal to the aggregate operator
(cell) vs what needs/can be exposed downstream (tuple). With the old
aggregate operator, this distinction was blurred as we wrapped the tuple
inside the monoid and use that as the cell too. This meant, technically,
downstream operators could call add, set, and rem.

With the new operator, because there are multiple monoids, it seemed a good
opportunity to clean this up a little to make sure the monoids aren't
accessible downstream (or within the specification via expressions, as the
monoids are namespaced by the field name).

On Monday, April 20, 2015, Dominik Moritz notifications@github.com wrote:

> The changes make sense to me. I'm still a bit shaky on the distinction
> between cell and tuple, though.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uwdata/vega/pull/40#issuecomment-94553121.

## 

## -Arvind

Arvind Satyanarayan http://arvindsatya.com/

**Pull request merged**
